// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `with_api`

/// Initialise against the hub at `base_url` (`http://192.168.4.1` on the
/// provisioning hotspot), or against the in-memory fake in mock mode.
Future<void> frbInit({required String baseUrl, required bool mock}) =>
    RustLib.instance.api.crateFrbApiFrbInit(baseUrl: baseUrl, mock: mock);

/// Point the client at a different hub address (keeps mock mode as-is if the
/// fake is active - the fake ignores addresses).
Future<void> frbSetHubAddress({required String baseUrl}) =>
    RustLib.instance.api.crateFrbApiFrbSetHubAddress(baseUrl: baseUrl);

/// Fetch the hub's configuration and live status in one go.
Future<HubSnapshot> frbLoadSnapshot() => RustLib.instance.api.crateFrbApiFrbLoadSnapshot();

/// Fetch just the live status.
Future<HubStatusView> frbGetStatus() => RustLib.instance.api.crateFrbApiFrbGetStatus();

/// Validate and apply a configuration update; on success the hub reboots
/// onto the configured network.
Future<ApplyOutcome> frbSaveConfig({required ConfigUpdate update}) =>
    RustLib.instance.api.crateFrbApiFrbSaveConfig(update: update);
