// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'frb_api.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart' if (dart.library.js_interop) 'frb_generated.web.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor => RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor => RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig => kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -1810031562;

  static const kDefaultExternalLibraryLoaderConfig = ExternalLibraryLoaderConfig(
    stem: 'rust_backend',
    ioDirectory: 'rust_backend/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<HubStatusView> crateFrbApiFrbGetStatus();

  Future<void> crateFrbApiFrbInit({required String baseUrl, required bool mock});

  Future<HubSnapshot> crateFrbApiFrbLoadSnapshot();

  Future<ApplyOutcome> crateFrbApiFrbSaveConfig({required ConfigUpdate update});

  Future<void> crateFrbApiFrbSetHubAddress({required String baseUrl});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<HubStatusView> crateFrbApiFrbGetStatus() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_hub_status_view, decodeErrorData: sse_decode_String),
        constMeta: kCrateFrbApiFrbGetStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiFrbGetStatusConstMeta => const TaskConstMeta(debugName: "frb_get_status", argNames: []);

  @override
  Future<void> crateFrbApiFrbInit({required String baseUrl, required bool mock}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(baseUrl, serializer);
          sse_encode_bool(mock, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_unit, decodeErrorData: sse_decode_String),
        constMeta: kCrateFrbApiFrbInitConstMeta,
        argValues: [baseUrl, mock],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiFrbInitConstMeta =>
      const TaskConstMeta(debugName: "frb_init", argNames: ["baseUrl", "mock"]);

  @override
  Future<HubSnapshot> crateFrbApiFrbLoadSnapshot() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_hub_snapshot, decodeErrorData: sse_decode_String),
        constMeta: kCrateFrbApiFrbLoadSnapshotConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiFrbLoadSnapshotConstMeta =>
      const TaskConstMeta(debugName: "frb_load_snapshot", argNames: []);

  @override
  Future<ApplyOutcome> crateFrbApiFrbSaveConfig({required ConfigUpdate update}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_config_update(update, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_apply_outcome, decodeErrorData: sse_decode_String),
        constMeta: kCrateFrbApiFrbSaveConfigConstMeta,
        argValues: [update],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiFrbSaveConfigConstMeta =>
      const TaskConstMeta(debugName: "frb_save_config", argNames: ["update"]);

  @override
  Future<void> crateFrbApiFrbSetHubAddress({required String baseUrl}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(baseUrl, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_unit, decodeErrorData: sse_decode_String),
        constMeta: kCrateFrbApiFrbSetHubAddressConstMeta,
        argValues: [baseUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiFrbSetHubAddressConstMeta =>
      const TaskConstMeta(debugName: "frb_set_hub_address", argNames: ["baseUrl"]);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  ApplyOutcome dco_decode_apply_outcome(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ApplyOutcome(ok: dco_decode_bool(arr[0]), rebooting: dco_decode_bool(arr[1]));
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ConfigUpdate dco_decode_box_autoadd_config_update(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_config_update(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_box_autoadd_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  ConfigUpdate dco_decode_config_update(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 12) throw Exception('unexpected arr length: expect 12 but see ${arr.length}');
    return ConfigUpdate(
      wifiSsid: dco_decode_opt_String(arr[0]),
      wifiPassword: dco_decode_opt_String(arr[1]),
      mqttHost: dco_decode_opt_String(arr[2]),
      mqttPort: dco_decode_opt_box_autoadd_u_16(arr[3]),
      clientId: dco_decode_opt_String(arr[4]),
      mode: dco_decode_opt_String(arr[5]),
      gwFreqHz: dco_decode_opt_box_autoadd_u_32(arr[6]),
      gwSf: dco_decode_opt_box_autoadd_u_8(arr[7]),
      gwBwKhz: dco_decode_opt_box_autoadd_u_32(arr[8]),
      gwCr: dco_decode_opt_box_autoadd_u_8(arr[9]),
      gwHost: dco_decode_opt_String(arr[10]),
      gwPort: dco_decode_opt_box_autoadd_u_16(arr[11]),
    );
  }

  @protected
  HubConfigView dco_decode_hub_config_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11) throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return HubConfigView(
      mode: dco_decode_String(arr[0]),
      wifiSsid: dco_decode_String(arr[1]),
      mqttHost: dco_decode_String(arr[2]),
      mqttPort: dco_decode_u_16(arr[3]),
      clientId: dco_decode_String(arr[4]),
      gwFreqHz: dco_decode_u_32(arr[5]),
      gwSf: dco_decode_u_8(arr[6]),
      gwBwKhz: dco_decode_u_32(arr[7]),
      gwCr: dco_decode_u_8(arr[8]),
      gwHost: dco_decode_String(arr[9]),
      gwPort: dco_decode_u_16(arr[10]),
    );
  }

  @protected
  HubSnapshot dco_decode_hub_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return HubSnapshot(config: dco_decode_hub_config_view(arr[0]), status: dco_decode_hub_status_view(arr[1]));
  }

  @protected
  HubStatusView dco_decode_hub_status_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7) throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return HubStatusView(
      wifiState: dco_decode_u_8(arr[0]),
      mqttState: dco_decode_u_8(arr[1]),
      ip: dco_decode_String(arr[2]),
      uplink: dco_decode_u_32(arr[3]),
      downlink: dco_decode_u_32(arr[4]),
      dropped: dco_decode_u_32(arr[5]),
      uptimeSecs: dco_decode_u_32(arr[6]),
    );
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_16(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_8(raw);
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  ApplyOutcome sse_decode_apply_outcome(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ok = sse_decode_bool(deserializer);
    var var_rebooting = sse_decode_bool(deserializer);
    return ApplyOutcome(ok: var_ok, rebooting: var_rebooting);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ConfigUpdate sse_decode_box_autoadd_config_update(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_config_update(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_16(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_8(deserializer));
  }

  @protected
  ConfigUpdate sse_decode_config_update(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_wifiSsid = sse_decode_opt_String(deserializer);
    var var_wifiPassword = sse_decode_opt_String(deserializer);
    var var_mqttHost = sse_decode_opt_String(deserializer);
    var var_mqttPort = sse_decode_opt_box_autoadd_u_16(deserializer);
    var var_clientId = sse_decode_opt_String(deserializer);
    var var_mode = sse_decode_opt_String(deserializer);
    var var_gwFreqHz = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_gwSf = sse_decode_opt_box_autoadd_u_8(deserializer);
    var var_gwBwKhz = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_gwCr = sse_decode_opt_box_autoadd_u_8(deserializer);
    var var_gwHost = sse_decode_opt_String(deserializer);
    var var_gwPort = sse_decode_opt_box_autoadd_u_16(deserializer);
    return ConfigUpdate(
      wifiSsid: var_wifiSsid,
      wifiPassword: var_wifiPassword,
      mqttHost: var_mqttHost,
      mqttPort: var_mqttPort,
      clientId: var_clientId,
      mode: var_mode,
      gwFreqHz: var_gwFreqHz,
      gwSf: var_gwSf,
      gwBwKhz: var_gwBwKhz,
      gwCr: var_gwCr,
      gwHost: var_gwHost,
      gwPort: var_gwPort,
    );
  }

  @protected
  HubConfigView sse_decode_hub_config_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_mode = sse_decode_String(deserializer);
    var var_wifiSsid = sse_decode_String(deserializer);
    var var_mqttHost = sse_decode_String(deserializer);
    var var_mqttPort = sse_decode_u_16(deserializer);
    var var_clientId = sse_decode_String(deserializer);
    var var_gwFreqHz = sse_decode_u_32(deserializer);
    var var_gwSf = sse_decode_u_8(deserializer);
    var var_gwBwKhz = sse_decode_u_32(deserializer);
    var var_gwCr = sse_decode_u_8(deserializer);
    var var_gwHost = sse_decode_String(deserializer);
    var var_gwPort = sse_decode_u_16(deserializer);
    return HubConfigView(
      mode: var_mode,
      wifiSsid: var_wifiSsid,
      mqttHost: var_mqttHost,
      mqttPort: var_mqttPort,
      clientId: var_clientId,
      gwFreqHz: var_gwFreqHz,
      gwSf: var_gwSf,
      gwBwKhz: var_gwBwKhz,
      gwCr: var_gwCr,
      gwHost: var_gwHost,
      gwPort: var_gwPort,
    );
  }

  @protected
  HubSnapshot sse_decode_hub_snapshot(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_config = sse_decode_hub_config_view(deserializer);
    var var_status = sse_decode_hub_status_view(deserializer);
    return HubSnapshot(config: var_config, status: var_status);
  }

  @protected
  HubStatusView sse_decode_hub_status_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_wifiState = sse_decode_u_8(deserializer);
    var var_mqttState = sse_decode_u_8(deserializer);
    var var_ip = sse_decode_String(deserializer);
    var var_uplink = sse_decode_u_32(deserializer);
    var var_downlink = sse_decode_u_32(deserializer);
    var var_dropped = sse_decode_u_32(deserializer);
    var var_uptimeSecs = sse_decode_u_32(deserializer);
    return HubStatusView(
      wifiState: var_wifiState,
      mqttState: var_mqttState,
      ip: var_ip,
      uplink: var_uplink,
      downlink: var_downlink,
      dropped: var_dropped,
      uptimeSecs: var_uptimeSecs,
    );
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_16(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_8(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_apply_outcome(ApplyOutcome self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.ok, serializer);
    sse_encode_bool(self.rebooting, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_config_update(ConfigUpdate self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_config_update(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self, serializer);
  }

  @protected
  void sse_encode_config_update(ConfigUpdate self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.wifiSsid, serializer);
    sse_encode_opt_String(self.wifiPassword, serializer);
    sse_encode_opt_String(self.mqttHost, serializer);
    sse_encode_opt_box_autoadd_u_16(self.mqttPort, serializer);
    sse_encode_opt_String(self.clientId, serializer);
    sse_encode_opt_String(self.mode, serializer);
    sse_encode_opt_box_autoadd_u_32(self.gwFreqHz, serializer);
    sse_encode_opt_box_autoadd_u_8(self.gwSf, serializer);
    sse_encode_opt_box_autoadd_u_32(self.gwBwKhz, serializer);
    sse_encode_opt_box_autoadd_u_8(self.gwCr, serializer);
    sse_encode_opt_String(self.gwHost, serializer);
    sse_encode_opt_box_autoadd_u_16(self.gwPort, serializer);
  }

  @protected
  void sse_encode_hub_config_view(HubConfigView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.mode, serializer);
    sse_encode_String(self.wifiSsid, serializer);
    sse_encode_String(self.mqttHost, serializer);
    sse_encode_u_16(self.mqttPort, serializer);
    sse_encode_String(self.clientId, serializer);
    sse_encode_u_32(self.gwFreqHz, serializer);
    sse_encode_u_8(self.gwSf, serializer);
    sse_encode_u_32(self.gwBwKhz, serializer);
    sse_encode_u_8(self.gwCr, serializer);
    sse_encode_String(self.gwHost, serializer);
    sse_encode_u_16(self.gwPort, serializer);
  }

  @protected
  void sse_encode_hub_snapshot(HubSnapshot self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_hub_config_view(self.config, serializer);
    sse_encode_hub_status_view(self.status, serializer);
  }

  @protected
  void sse_encode_hub_status_view(HubStatusView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self.wifiState, serializer);
    sse_encode_u_8(self.mqttState, serializer);
    sse_encode_String(self.ip, serializer);
    sse_encode_u_32(self.uplink, serializer);
    sse_encode_u_32(self.downlink, serializer);
    sse_encode_u_32(self.dropped, serializer);
    sse_encode_u_32(self.uptimeSecs, serializer);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_16(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_8(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_8(self, serializer);
    }
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
