// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// `POST /api/config` reply.
class ApplyOutcome {
  final bool ok;
  final bool rebooting;

  const ApplyOutcome({required this.ok, required this.rebooting});

  @override
  int get hashCode => ok.hashCode ^ rebooting.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApplyOutcome && runtimeType == other.runtimeType && ok == other.ok && rebooting == other.rebooting;
}

/// `POST /api/config` body: only the present fields change.
class ConfigUpdate {
  final String? wifiSsid;
  final String? wifiPassword;
  final String? mqttHost;
  final int? mqttPort;
  final String? clientId;
  final String? mode;
  final int? gwFreqHz;
  final int? gwSf;
  final int? gwBwKhz;
  final int? gwCr;
  final String? gwHost;
  final int? gwPort;

  const ConfigUpdate({
    this.wifiSsid,
    this.wifiPassword,
    this.mqttHost,
    this.mqttPort,
    this.clientId,
    this.mode,
    this.gwFreqHz,
    this.gwSf,
    this.gwBwKhz,
    this.gwCr,
    this.gwHost,
    this.gwPort,
  });

  @override
  int get hashCode =>
      wifiSsid.hashCode ^
      wifiPassword.hashCode ^
      mqttHost.hashCode ^
      mqttPort.hashCode ^
      clientId.hashCode ^
      mode.hashCode ^
      gwFreqHz.hashCode ^
      gwSf.hashCode ^
      gwBwKhz.hashCode ^
      gwCr.hashCode ^
      gwHost.hashCode ^
      gwPort.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConfigUpdate &&
          runtimeType == other.runtimeType &&
          wifiSsid == other.wifiSsid &&
          wifiPassword == other.wifiPassword &&
          mqttHost == other.mqttHost &&
          mqttPort == other.mqttPort &&
          clientId == other.clientId &&
          mode == other.mode &&
          gwFreqHz == other.gwFreqHz &&
          gwSf == other.gwSf &&
          gwBwKhz == other.gwBwKhz &&
          gwCr == other.gwCr &&
          gwHost == other.gwHost &&
          gwPort == other.gwPort;
}

/// `GET /api/config` (the hub never includes the WiFi password).
class HubConfigView {
  final String mode;
  final String wifiSsid;
  final String mqttHost;
  final int mqttPort;
  final String clientId;
  final int gwFreqHz;
  final int gwSf;
  final int gwBwKhz;
  final int gwCr;
  final String gwHost;
  final int gwPort;

  const HubConfigView({
    required this.mode,
    required this.wifiSsid,
    required this.mqttHost,
    required this.mqttPort,
    required this.clientId,
    required this.gwFreqHz,
    required this.gwSf,
    required this.gwBwKhz,
    required this.gwCr,
    required this.gwHost,
    required this.gwPort,
  });

  @override
  int get hashCode =>
      mode.hashCode ^
      wifiSsid.hashCode ^
      mqttHost.hashCode ^
      mqttPort.hashCode ^
      clientId.hashCode ^
      gwFreqHz.hashCode ^
      gwSf.hashCode ^
      gwBwKhz.hashCode ^
      gwCr.hashCode ^
      gwHost.hashCode ^
      gwPort.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HubConfigView &&
          runtimeType == other.runtimeType &&
          mode == other.mode &&
          wifiSsid == other.wifiSsid &&
          mqttHost == other.mqttHost &&
          mqttPort == other.mqttPort &&
          clientId == other.clientId &&
          gwFreqHz == other.gwFreqHz &&
          gwSf == other.gwSf &&
          gwBwKhz == other.gwBwKhz &&
          gwCr == other.gwCr &&
          gwHost == other.gwHost &&
          gwPort == other.gwPort;
}

/// Both halves of what the connect screen needs in one round trip.
class HubSnapshot {
  final HubConfigView config;
  final HubStatusView status;

  const HubSnapshot({required this.config, required this.status});

  @override
  int get hashCode => config.hashCode ^ status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HubSnapshot && runtimeType == other.runtimeType && config == other.config && status == other.status;
}

/// `GET /api/status`.
class HubStatusView {
  final int wifiState;
  final int mqttState;
  final String ip;
  final int uplink;
  final int downlink;
  final int dropped;
  final int uptimeSecs;

  const HubStatusView({
    required this.wifiState,
    required this.mqttState,
    required this.ip,
    required this.uplink,
    required this.downlink,
    required this.dropped,
    required this.uptimeSecs,
  });

  @override
  int get hashCode =>
      wifiState.hashCode ^
      mqttState.hashCode ^
      ip.hashCode ^
      uplink.hashCode ^
      downlink.hashCode ^
      dropped.hashCode ^
      uptimeSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HubStatusView &&
          runtimeType == other.runtimeType &&
          wifiState == other.wifiState &&
          mqttState == other.mqttState &&
          ip == other.ip &&
          uplink == other.uplink &&
          downlink == other.downlink &&
          dropped == other.dropped &&
          uptimeSecs == other.uptimeSecs;
}
