// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.11.1";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -1810031562;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__frb_api__frb_get_status_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "frb_get_status",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::frb_api::frb_get_status()?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__frb_api__frb_init_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "frb_init",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_base_url = <String>::sse_decode(&mut deserializer);
            let api_mock = <bool>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::frb_api::frb_init(api_base_url, api_mock)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__frb_api__frb_load_snapshot_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "frb_load_snapshot",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::frb_api::frb_load_snapshot()?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__frb_api__frb_save_config_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "frb_save_config",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_update = <crate::models::ConfigUpdate>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::frb_api::frb_save_config(api_update)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__frb_api__frb_set_hub_address_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "frb_set_hub_address",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_base_url = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::frb_api::frb_set_hub_address(api_base_url)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}

// Section: dart2rust

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for crate::models::ApplyOutcome {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_ok = <bool>::sse_decode(deserializer);
        let mut var_rebooting = <bool>::sse_decode(deserializer);
        return crate::models::ApplyOutcome {
            ok: var_ok,
            rebooting: var_rebooting,
        };
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::models::ConfigUpdate {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_wifiSsid = <Option<String>>::sse_decode(deserializer);
        let mut var_wifiPassword = <Option<String>>::sse_decode(deserializer);
        let mut var_mqttHost = <Option<String>>::sse_decode(deserializer);
        let mut var_mqttPort = <Option<u16>>::sse_decode(deserializer);
        let mut var_clientId = <Option<String>>::sse_decode(deserializer);
        let mut var_mode = <Option<String>>::sse_decode(deserializer);
        let mut var_gwFreqHz = <Option<u32>>::sse_decode(deserializer);
        let mut var_gwSf = <Option<u8>>::sse_decode(deserializer);
        let mut var_gwBwKhz = <Option<u32>>::sse_decode(deserializer);
        let mut var_gwCr = <Option<u8>>::sse_decode(deserializer);
        let mut var_gwHost = <Option<String>>::sse_decode(deserializer);
        let mut var_gwPort = <Option<u16>>::sse_decode(deserializer);
        return crate::models::ConfigUpdate {
            wifi_ssid: var_wifiSsid,
            wifi_password: var_wifiPassword,
            mqtt_host: var_mqttHost,
            mqtt_port: var_mqttPort,
            client_id: var_clientId,
            mode: var_mode,
            gw_freq_hz: var_gwFreqHz,
            gw_sf: var_gwSf,
            gw_bw_khz: var_gwBwKhz,
            gw_cr: var_gwCr,
            gw_host: var_gwHost,
            gw_port: var_gwPort,
        };
    }
}

impl SseDecode for crate::models::HubConfigView {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_mode = <String>::sse_decode(deserializer);
        let mut var_wifiSsid = <String>::sse_decode(deserializer);
        let mut var_mqttHost = <String>::sse_decode(deserializer);
        let mut var_mqttPort = <u16>::sse_decode(deserializer);
        let mut var_clientId = <String>::sse_decode(deserializer);
        let mut var_gwFreqHz = <u32>::sse_decode(deserializer);
        let mut var_gwSf = <u8>::sse_decode(deserializer);
        let mut var_gwBwKhz = <u32>::sse_decode(deserializer);
        let mut var_gwCr = <u8>::sse_decode(deserializer);
        let mut var_gwHost = <String>::sse_decode(deserializer);
        let mut var_gwPort = <u16>::sse_decode(deserializer);
        return crate::models::HubConfigView {
            mode: var_mode,
            wifi_ssid: var_wifiSsid,
            mqtt_host: var_mqttHost,
            mqtt_port: var_mqttPort,
            client_id: var_clientId,
            gw_freq_hz: var_gwFreqHz,
            gw_sf: var_gwSf,
            gw_bw_khz: var_gwBwKhz,
            gw_cr: var_gwCr,
            gw_host: var_gwHost,
            gw_port: var_gwPort,
        };
    }
}

impl SseDecode for crate::models::HubSnapshot {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_config = <crate::models::HubConfigView>::sse_decode(deserializer);
        let mut var_status = <crate::models::HubStatusView>::sse_decode(deserializer);
        return crate::models::HubSnapshot {
            config: var_config,
            status: var_status,
        };
    }
}

impl SseDecode for crate::models::HubStatusView {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_wifiState = <u8>::sse_decode(deserializer);
        let mut var_mqttState = <u8>::sse_decode(deserializer);
        let mut var_ip = <String>::sse_decode(deserializer);
        let mut var_uplink = <u32>::sse_decode(deserializer);
        let mut var_downlink = <u32>::sse_decode(deserializer);
        let mut var_dropped = <u32>::sse_decode(deserializer);
        let mut var_uptimeSecs = <u32>::sse_decode(deserializer);
        return crate::models::HubStatusView {
            wifi_state: var_wifiState,
            mqtt_state: var_mqttState,
            ip: var_ip,
            uplink: var_uplink,
            downlink: var_downlink,
            dropped: var_dropped,
            uptime_secs: var_uptimeSecs,
        };
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u16> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u16>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u32>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u8>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for u16 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u16::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__frb_api__frb_get_status_impl(port, ptr, rust_vec_len, data_len),
        2 => wire__crate__frb_api__frb_init_impl(port, ptr, rust_vec_len, data_len),
        3 => wire__crate__frb_api__frb_load_snapshot_impl(port, ptr, rust_vec_len, data_len),
        4 => wire__crate__frb_api__frb_save_config_impl(port, ptr, rust_vec_len, data_len),
        5 => wire__crate__frb_api__frb_set_hub_address_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::models::ApplyOutcome {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.ok.into_into_dart().into_dart(),
            self.rebooting.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::models::ApplyOutcome {}
impl flutter_rust_bridge::IntoIntoDart<crate::models::ApplyOutcome>
    for crate::models::ApplyOutcome
{
    fn into_into_dart(self) -> crate::models::ApplyOutcome {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::models::ConfigUpdate {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.wifi_ssid.into_into_dart().into_dart(),
            self.wifi_password.into_into_dart().into_dart(),
            self.mqtt_host.into_into_dart().into_dart(),
            self.mqtt_port.into_into_dart().into_dart(),
            self.client_id.into_into_dart().into_dart(),
            self.mode.into_into_dart().into_dart(),
            self.gw_freq_hz.into_into_dart().into_dart(),
            self.gw_sf.into_into_dart().into_dart(),
            self.gw_bw_khz.into_into_dart().into_dart(),
            self.gw_cr.into_into_dart().into_dart(),
            self.gw_host.into_into_dart().into_dart(),
            self.gw_port.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::models::ConfigUpdate {}
impl flutter_rust_bridge::IntoIntoDart<crate::models::ConfigUpdate>
    for crate::models::ConfigUpdate
{
    fn into_into_dart(self) -> crate::models::ConfigUpdate {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::models::HubConfigView {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.mode.into_into_dart().into_dart(),
            self.wifi_ssid.into_into_dart().into_dart(),
            self.mqtt_host.into_into_dart().into_dart(),
            self.mqtt_port.into_into_dart().into_dart(),
            self.client_id.into_into_dart().into_dart(),
            self.gw_freq_hz.into_into_dart().into_dart(),
            self.gw_sf.into_into_dart().into_dart(),
            self.gw_bw_khz.into_into_dart().into_dart(),
            self.gw_cr.into_into_dart().into_dart(),
            self.gw_host.into_into_dart().into_dart(),
            self.gw_port.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::models::HubConfigView {}
impl flutter_rust_bridge::IntoIntoDart<crate::models::HubConfigView>
    for crate::models::HubConfigView
{
    fn into_into_dart(self) -> crate::models::HubConfigView {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::models::HubSnapshot {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.config.into_into_dart().into_dart(),
            self.status.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::models::HubSnapshot {}
impl flutter_rust_bridge::IntoIntoDart<crate::models::HubSnapshot> for crate::models::HubSnapshot {
    fn into_into_dart(self) -> crate::models::HubSnapshot {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::models::HubStatusView {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.wifi_state.into_into_dart().into_dart(),
            self.mqtt_state.into_into_dart().into_dart(),
            self.ip.into_into_dart().into_dart(),
            self.uplink.into_into_dart().into_dart(),
            self.downlink.into_into_dart().into_dart(),
            self.dropped.into_into_dart().into_dart(),
            self.uptime_secs.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::models::HubStatusView {}
impl flutter_rust_bridge::IntoIntoDart<crate::models::HubStatusView>
    for crate::models::HubStatusView
{
    fn into_into_dart(self) -> crate::models::HubStatusView {
        self
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for crate::models::ApplyOutcome {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.ok, serializer);
        <bool>::sse_encode(self.rebooting, serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::models::ConfigUpdate {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Option<String>>::sse_encode(self.wifi_ssid, serializer);
        <Option<String>>::sse_encode(self.wifi_password, serializer);
        <Option<String>>::sse_encode(self.mqtt_host, serializer);
        <Option<u16>>::sse_encode(self.mqtt_port, serializer);
        <Option<String>>::sse_encode(self.client_id, serializer);
        <Option<String>>::sse_encode(self.mode, serializer);
        <Option<u32>>::sse_encode(self.gw_freq_hz, serializer);
        <Option<u8>>::sse_encode(self.gw_sf, serializer);
        <Option<u32>>::sse_encode(self.gw_bw_khz, serializer);
        <Option<u8>>::sse_encode(self.gw_cr, serializer);
        <Option<String>>::sse_encode(self.gw_host, serializer);
        <Option<u16>>::sse_encode(self.gw_port, serializer);
    }
}

impl SseEncode for crate::models::HubConfigView {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.mode, serializer);
        <String>::sse_encode(self.wifi_ssid, serializer);
        <String>::sse_encode(self.mqtt_host, serializer);
        <u16>::sse_encode(self.mqtt_port, serializer);
        <String>::sse_encode(self.client_id, serializer);
        <u32>::sse_encode(self.gw_freq_hz, serializer);
        <u8>::sse_encode(self.gw_sf, serializer);
        <u32>::sse_encode(self.gw_bw_khz, serializer);
        <u8>::sse_encode(self.gw_cr, serializer);
        <String>::sse_encode(self.gw_host, serializer);
        <u16>::sse_encode(self.gw_port, serializer);
    }
}

impl SseEncode for crate::models::HubSnapshot {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::models::HubConfigView>::sse_encode(self.config, serializer);
        <crate::models::HubStatusView>::sse_encode(self.status, serializer);
    }
}

impl SseEncode for crate::models::HubStatusView {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u8>::sse_encode(self.wifi_state, serializer);
        <u8>::sse_encode(self.mqtt_state, serializer);
        <String>::sse_encode(self.ip, serializer);
        <u32>::sse_encode(self.uplink, serializer);
        <u32>::sse_encode(self.downlink, serializer);
        <u32>::sse_encode(self.dropped, serializer);
        <u32>::sse_encode(self.uptime_secs, serializer);
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u16> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u16>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u32>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u8>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for u16 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u16::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
